minimumReleaseAgeExclude:
  - rolldown-plugin-dts@0.27.8
  - tsdown@0.22.7
  - '@antfu/eslint-config@9.2.0'
  - lint-staged@17.1.1

shellEmulator: true

packages:
  - playground

overrides:
  unrouting: 'link:.'

allowBuilds:
  esbuild: false
  simple-git-hooks: true
